(defpackage #:mrjam-identite
  (:use #:cl)
  (:export #:faire-client #:requete #:autorisation #:adresse-verifiee #:issuer #:identite-error #:reponse-statut #:reponse-json #:reponse-location #:parametre-url))
(in-package #:mrjam-identite)
(define-condition identite-error (error) ())
(defun refuse () (error 'identite-error))
(defparameter issuer "https://log.mrj.am/realms/mrjam")
(defstruct (client (:constructor %faire-client)) id secret base curl)
(defstruct reponse statut json location)
(defun faire-client (id secret curl &key (base "http://127.0.0.1:8085"))
  (unless (and (member id '("mrjam-cycle" "mrjam-admission" "mrjam-fermeture") :test #'equal)
               (mrjam-courriel::ascii-p secret "_-" 43 43)
               (uiop:absolute-pathname-p curl) (probe-file curl)
               (uiop:string-prefix-p "http://127.0.0.1:" base)
               (every (lambda (c) (char<= #\0 c #\9)) (subseq base 17))
               (<= 1 (parse-integer base :start 17) 65535)) (refuse))
  (%faire-client :id id :secret secret :base base :curl curl))
(defun parametre-url (s)
  (unless (stringp s) (refuse))
  (with-output-to-string (o)
    (loop for b across (sb-ext:string-to-octets s :external-format :utf-8) do
      (if (or (<= 65 b 90) (<= 97 b 122) (<= 48 b 57) (member b '(45 46 95 126)))
          (write-char (code-char b) o) (format o "%~2,'0X" b)))))

(defun lire-reponse (s)
  (let* ((v (make-array (* 2 1024 1024) :element-type 'character)) (n (read-sequence v s))
         (text (subseq v 0 n)) (fin (search (format nil "~C~C~C~C" #\Return #\Newline #\Return #\Newline) text)))
    (unless (and fin (< n (length v))) (refuse))
    (let* ((lines (uiop:split-string (subseq text 0 fin) :separator (string #\Newline)))
           (parts (uiop:split-string (first lines) :separator " "))
           (status (and (second parts) (parse-integer (second parts) :junk-allowed nil)))
           (location nil) (body (subseq text (+ fin 4))))
      (unless (and status (<= 100 status 599)) (refuse))
      (dolist (l (rest lines))
        (when (uiop:string-prefix-p "location:" (string-downcase l))
          (setf location (string-trim '(#\Space #\Tab #\Return) (subseq l 9)))))
      ;; Une réponse d'erreur HTML n'est jamais montrée ni inscrite au journal.
      (make-reponse :statut status :json (when (> (length body) 0) (handler-case (vision:parse-json body) (error () nil))) :location location))))

(defun requete (client methode path &key token json form)
  "API loopback de l'IdP officiel ; secrets sur pipe, réponses bornées, aucun redirect."
  (unless (and (member methode '("GET" "POST" "PUT" "DELETE") :test #'equal) (stringp path)
               (<= 1 (length path) 2048) (not (find #\Return path)) (not (find #\Newline path))
               (or (equal path "/admin/realms/mrjam/users")
                   (uiop:string-prefix-p "/admin/realms/mrjam/users/" path)
                   (uiop:string-prefix-p "/admin/realms/mrjam/users?" path)
                   (equal path "/realms/mrjam/protocol/openid-connect/token"))
               (not (and json form))) (refuse))
  (let ((route (string-downcase (subseq path 0 (position #\? path)))))
    (when (or (search "%2e" route) (search "%2f" route)
              (some (lambda (s) (member s '("." "..") :test #'equal)) (uiop:split-string route :separator "/"))) (refuse)))
  (let* ((data (cond (json (mrjam-native:json-js json)) (form form)))
         (p nil))
    (labels ((executer (fichier)
               (let ((input (with-output-to-string (o)
                              (format o "silent~%show-error~%max-time = 10~%connect-timeout = 5~%max-filesize = 2097152~%proxy = \"\"~%noproxy = \"*\"~%proto = \"=http\"~%")
                              (format o "url = ~A~%request = ~A~%dump-header = \"-\"~%"
                                      (mrjam-courriel::config-curl (concatenate 'string (client-base client) path)) (mrjam-courriel::config-curl methode))
                              (when token
                                (unless (mrjam-courriel::ascii-p token "_.-" 1 65536) (refuse))
                                (format o "header = ~A~%" (mrjam-courriel::config-curl (concatenate 'string "Authorization: Bearer " token))))
                              (when fichier
                                (format o "header = ~A~%data-binary = ~A~%"
                                        (mrjam-courriel::config-curl (if json "Content-Type: application/json" "Content-Type: application/x-www-form-urlencoded"))
                                        (mrjam-courriel::config-curl (concatenate 'string "@" (namestring fichier)))))
                              (format o "header = \"Expect:\"~%"))))
                 (unwind-protect
                     (sb-ext:with-timeout 15
                       (setf p (sb-ext:run-program (client-curl client) '("--disable" "--config" "-")
                                      :input :stream :output :stream :error nil :wait nil :external-format :utf-8))
                       (write-string input (sb-ext:process-input p)) (finish-output (sb-ext:process-input p)) (close (sb-ext:process-input p))
                       (let ((response (lire-reponse (sb-ext:process-output p))))
                         (sb-ext:process-wait p) (unless (eql (sb-ext:process-exit-code p) 0) (refuse)) response))
                   (when p (when (sb-ext:process-alive-p p) (sb-ext:process-kill p sb-posix:sigkill)) (sb-ext:process-close p))))))
      (if data (mrjam-courriel::avec-temporaire (sb-ext:string-to-octets data :external-format :utf-8) #'executer) (executer nil)))))

(defun autorisation (client)
  (let* ((r (requete client "POST" "/realms/mrjam/protocol/openid-connect/token"
                    :form (format nil "grant_type=client_credentials&client_id=~A&client_secret=~A" (parametre-url (client-id client)) (parametre-url (client-secret client)))))
         (token (vision:json-object-get (reponse-json r) "access_token")))
    (unless (and (= (reponse-statut r) 200) (stringp token)) (refuse)) token))

(defun adresse-verifiee (client demande)
  (let ((sujet (vision:json-object-get demande "sujet")))
    (unless (and (equal (vision:json-object-get demande "emetteur") issuer) (mrjam-courriel::ascii-p sujet "_.-" 1 64)) (refuse))
    (let* ((r (requete client "GET" (concatenate 'string "/admin/realms/mrjam/users/" (parametre-url sujet)) :token (autorisation client)))
           (profil (reponse-json r)))
      (unless (and (= (reponse-statut r) 200) (equal (vision:json-object-get profil "id") sujet) (eq :true (vision:json-object-get profil "emailVerified"))) (refuse))
      (mrjam-courriel:adresse (vision:json-object-get profil "email")))))
