(defpackage #:admission-composant (:use #:cl) (:export #:verifier))
(in-package #:admission-composant)
(defun verifier (dsn root base curl)
  (let* ((admin (concatenate 'string (subseq dsn 0 (search "user=vision " dsn)) "user=vision_administration dbname=vision_native_test"))
         (admission-dsn (concatenate 'string (subseq dsn 0 (search "user=vision " dsn)) "user=vision_admission dbname=vision_native_test"))
         (smtp (vision:jobject "host" "smtp.protonmail.ch" "port" 587 "username" "sender@example.test" "password" "SyntheseSMTP2026Token" "from_address" "sender@example.test" "starttls_required" :true "certificate_verification" :true))
         (client (mrjam-identite:faire-client "mrjam-admission" (make-string 43 :initial-element #\a) curl :base base))
         (ctx (vision-admission:faire-admission admission-dsn (merge-pathnames "admission/" (uiop:ensure-directory-pathname root)) smtp client))
         (inv (vision-administration:administrer admin "alice" "creer_invitation" (vision:jobject "intitule" "Qualification synthétique" "maximum" 10 "expire_a"
                    (progn
                      (multiple-value-bind (ss mm hh dd mo yy) (decode-universal-time (+ (get-universal-time) 86400) 0)
                        (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ" yy mo dd hh mm ss))))))
         (secret (subseq (vision:json-object-get inv "lien") (1+ (position #\# (vision:json-object-get inv "lien")))))
         (file (vision-admission::admission-file ctx)))
    (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) t))
    (labels ((demander (email age &optional (parent ""))
               (vision-admission:demander ctx (vision:jobject "invitation" secret "notice" "notice-test" "courriel" email "pays" "France" "age" age "parent" parent "pseudonyme" "Pseudo")))
             (rows () (vision-admission::ouvrir ctx (lambda (db) (mrjam-native:sqlite-requete db "SELECT * FROM demandes ORDER BY cree,id"))))
             (row (email) (find email (rows) :key (lambda (d) (vision-admission::j d "courriel")) :test #'equal))
             (token (id prefix)
               (let* ((r (mrjam-courriel::avec-file file (lambda (db) (first (mrjam-native:sqlite-requete db "SELECT message FROM courriels WHERE cle=?" (list (concatenate 'string prefix id)))))))
                      (wire (cdr (assoc "message" r :test #'equal))) (txt (fourth (mrjam-courriel::ancien-contenu wire)))
                      (start (search "https://vision.mrj.am/admission#" txt)))
                 (let ((a (+ start (length "https://vision.mrj.am/admission#")))) (subseq txt a (+ a 43))))))
      (demander "new@example.test" "majeur")
      (demander "new@example.test" "majeur") (assert (= 1 (length (rows))))
      (vision-admission:traiter ctx) (assert (equal "attente" (vision-admission::j (row "new@example.test") "etat")))
      (let ((tok (token (vision-admission::j (row "new@example.test") "id") "admission:")))
        (assert (equal "adresse" (vision:json-object-get (vision-admission:apercu ctx tok) "type")))
        (assert (handler-case (progn (vision-admission:confirmer ctx tok :false) nil) (vision-admission:admission-error () t)))
        (vision-admission:confirmer ctx tok :true)
        (assert (handler-case (progn (vision-admission:confirmer ctx tok :true) nil) (vision-admission:admission-error () t))))
      (vision-admission:traiter ctx) (assert (equal "admise" (vision-admission::j (row "new@example.test") "etat")))
      (let ((s (vision-admission::j (row "new@example.test") "sujet")))
        (assert (not (vision:json-object-get (vision-admission::sql ctx :identifier mrjam-identite:issuer s) "erreur"))))
      (demander "child@example.test" "moins15" "parent@example.test")
      (let* ((id (vision-admission::j (row "child@example.test") "id")) (v (token id "admission:")) (p (token id "parent:")))
        (vision-admission:confirmer ctx v :true)
        (vision-admission:traiter ctx) (assert (equal "attente" (vision-admission::j (row "child@example.test") "etat")))
        (assert (handler-case (progn (vision-admission:approuver ctx id "entretien" "Contrôle synthétique" "https://official.example.test") nil) (vision-admission:admission-error () t)))
        (vision-admission:confirmer ctx p :true)
        (vision-admission:traiter ctx) (assert (equal "attente" (vision-admission::j (row "child@example.test") "etat")))
        (assert (handler-case (progn (vision-admission:approuver ctx id "controle_pays" "Contrôle synthétique" "https://official.example.test") nil) (vision-admission:admission-error () t)))
        (vision-admission:approuver ctx id "verification_relation" "Contrôle synthétique" "https://official.example.test"))
      (vision-admission:traiter ctx) (assert (equal "admise" (vision-admission::j (row "child@example.test") "etat")))
      (demander "unverified@example.test" "majeur")
      (vision-admission:confirmer ctx (token (vision-admission::j (row "unverified@example.test") "id") "admission:") :true)
      (vision-admission:traiter ctx) (assert (equal "attente" (vision-admission::j (row "unverified@example.test") "etat")))
      (demander "alice@example.test" "majeur")
      (vision-admission:confirmer ctx (token (vision-admission::j (row "alice@example.test") "id") "admission:") :true)
      (vision-admission:traiter ctx) (assert (equal "sujet-alice" (vision-admission::j (row "alice@example.test") "sujet")))
      ;; Une admission du même sujet vérifié conserve son propriétaire et ses fiches.
      (let ((v (funcall (mrjam-metier::executeur-vision dsn) "qualification" "SELECT to_jsonb(contenu) FROM vision_fiches" '(("utilisateur" . "alice")))))
        (assert (equal v "Texte Alice")))
      (assert (= 403 (mrjam-metier::traiter-admission ctx "POST" "/auth/admission" nil "{}")))
      (assert (= 400 (mrjam-metier::traiter-admission ctx "POST" "/auth/admission/confirmer" '(("origin" . "https://vision.mrj.am") ("content-type" . "application/json")) "{\"token\":\"malforme\",\"acceptation\":true}")))
      (format t "Admission : invitation, doublons, confirmation unique, consentement parental, contrôle manuel et compte existant vérifié qualifiés hors production.~%")
      (values ctx (vision-admission::j (row "new@example.test") "sujet")))))
