(defpackage #:admission-differentiel (:use #:cl) (:export #:verifier))
(in-package #:admission-differentiel)
(defun verifier (fichier)
  (let ((n 0))
    (dolist (c (vision:json-array-items (vision:parse-json (uiop:read-file-string fichier))))
      (let ((actual (handler-case (vision-admission:verifier (vision:json-object-get c "input"))
                      (vision-admission:admission-error () :null) (mrjam-courriel:courriel-error () :null)))
            (expected (vision:json-object-get c "result")))
        (assert (equal (mrjam-native:json-js actual) (mrjam-native:json-js expected)) () "Admission synthétique ~D divergente." n)) (incf n))
    (format t "~D cas d'admission : consentement, pays, parent distinct et valeurs normalisées conformes.~%" n)))
