(defpackage #:courriel-composant (:use #:cl) (:export #:verifier))
(in-package #:courriel-composant)
(defun verifier (root)
  (let* ((root (uiop:ensure-directory-pathname root)) (path (merge-pathnames "courriels.sqlite" root))
         (env (mrjam-courriel:verifier-smtp (mrjam-courriel:lire-prive (merge-pathnames "smtp.json" root))))
         (env-insecure (vision::%make-json-object (copy-tree (vision:json-object-entries env))))
         (sends 0)
         (file (mrjam-courriel:faire-file path "sender@example.test" :transport (lambda (c m) (declare (ignore c m)) (incf sends)))))
    (setf (cdr (assoc "certificate_verification" (vision:json-object-entries env-insecure) :test #'equal)) :false)
    (assert (handler-case (progn (mrjam-courriel:verifier-smtp env-insecure) nil) (mrjam-courriel:courriel-error () t)))
    (dolist (p '("public.json" "lien.json"))
      (assert (handler-case (progn (mrjam-courriel:lire-prive (merge-pathnames p root)) nil) (error () t))))
    (dolist (c (vision:json-array-items (vision:parse-json (uiop:read-file-string (merge-pathnames "cas.json" root)))))
      (let ((piece (vision:json-object-get c "piece")))
        (mrjam-courriel:ajouter file (vision:json-object-get c "cle") "alice@example.test"
          (vision:json-object-get c "subject") (vision:json-object-get c "text")
          (unless (eq piece :null) (mrjam-courriel::de-base64 piece)))))
    (assert (handler-case (progn (mrjam-courriel:ajouter file "ancien:0" "bob@example.test" "MrJ.am — épreuve synthétique" (format nil "Une épreuve.~%Second paragraphe.")) nil)
              (mrjam-courriel:courriel-error () t)))
    (let* ((piece (make-array 5 :element-type '(unsigned-byte 8) :initial-contents '(0 255 97 98 99)))
           (sujet (concatenate 'string "Une épreuve — " (make-string 90 :initial-element #\é)))
           (texte (format nil "Texte é~%Zéro 0")))
      (mrjam-courriel:ajouter file "nouveau:1" "alice@example.test" sujet texte piece)
      (let ((threads (loop repeat 8 collect (sb-thread:make-thread (lambda () (mrjam-courriel:ajouter file "nouveau:1" "alice@example.test" sujet texte piece))))))
        (dolist (thr threads) (sb-thread:join-thread thr))))
    (mrjam-courriel:traiter file env :maintenant 2000000000)
    (assert (= sends 5))
    (assert (equal "accepte_relais" (vision:json-object-get (mrjam-courriel:etat file "ancien:0") "etat")))
    (mrjam-courriel:traiter file env :maintenant 2000000001) (assert (= sends 5))
    (mrjam-courriel:ajouter file "annule:1" "alice@example.test" "Annulation" "Synthétique")
    (mrjam-courriel:annuler file "annule:1") (mrjam-courriel:traiter file env :maintenant 2000000001) (assert (= sends 5))
    ;; Garder les anciens blobs pour la vérification indépendante Python.
    (mrjam-courriel:purger file 2000000001)
    (let* ((failed (mrjam-courriel:faire-file (merge-pathnames "erreurs.sqlite" root) "sender@example.test"
                      :transport (lambda (c m) (declare (ignore c m)) (error "Erreur synthétique"))))
           (now (mrjam-courriel:maintenant)))
      (mrjam-courriel:ajouter failed "erreur:1" "alice@example.test" "Épreuve" "Erreur synthétique")
      (mrjam-courriel:traiter failed env :maintenant now)
      (assert (= 1 (vision:json-object-get (mrjam-courriel:etat failed "erreur:1") "essais")))
      (mrjam-courriel:traiter failed env :maintenant (+ now 59))
      (assert (= 1 (vision:json-object-get (mrjam-courriel:etat failed "erreur:1") "essais")))
      (mrjam-courriel:traiter failed env :maintenant (+ now 60))
      (assert (= 2 (vision:json-object-get (mrjam-courriel:etat failed "erreur:1") "essais"))))
    (let* ((p (merge-pathnames "journal.jsonl" root)) (value (vision:jobject "utilisateur" "alice" "confirmee_a" 2000000000)))
      (mrjam-courriel:journal-ajouter p "utilisateur" "alice" (lambda () value))
      (mrjam-courriel:journal-ajouter p "utilisateur" "alice" (lambda () (error "Intention dupliquée")))
      (assert (= 1 (length (mrjam-courriel:journal-lire p)))))
    (format t "Files courriel : ancien MIME, idempotence concurrente, refus des fichiers publics, annulation et réessai borné réussis.~%")))
