(defpackage #:fermeture-composant (:use #:cl) (:export #:verifier))
(in-package #:fermeture-composant)
(defun verifier (dsn root base curl admission sujet)
  (let* ((fermeture-dsn (concatenate 'string (subseq dsn 0 (search "user=vision " dsn)) "user=vision_fermeture dbname=vision_native_test"))
         (smtp (vision-admission::admission-smtp admission))
         (client (mrjam-identite:faire-client "mrjam-fermeture" (make-string 43 :initial-element #\a) curl :base base))
         (ctx (vision-fermeture:faire-fermeture fermeture-dsn (merge-pathnames "fermeture/" (uiop:ensure-directory-pathname root)) smtp
                (vision:jobject "adresse_exploitant" "operator@example.test" "recipient_age" (concatenate 'string "age1" (make-string 58 :initial-element #\q)))
                client admission "/usr/bin/false"))
         (file (vision-fermeture::fermeture-file ctx))
         (secret (make-string 43 :initial-element #\b))
         (body (mrjam-native:json-js (vision:jobject "emetteur" mrjam-identite:issuer "sujet" sujet "confirmation" "FERMER MON COMPTE")))
         (headers (list (cons "authorization" (concatenate 'string "Bearer " secret)) (cons "content-type" "application/json"))))
    (assert (= 403 (mrjam-metier::traiter-fermeture ctx secret "POST" "/fermer" nil body)))
    (assert (= 400 (mrjam-metier::traiter-fermeture ctx secret "POST" "/fermer" headers "{\"emetteur\":\"faux\",\"sujet\":\"x\",\"confirmation\":\"FERMER MON COMPTE\"}")))
    (assert (handler-case (progn (vision-fermeture:preparer ctx sujet "FAUX") nil) (vision-fermeture:fermeture-error () t)))
    (assert (handler-case (progn (vision-fermeture::retirer-identite ctx sujet) nil) (vision-fermeture:fermeture-error () t)))
    (let* ((p (vision-fermeture::registre ctx sujet))
           (cle (concatenate 'string "fermeture:" (mrjam-native:sha256 (format nil "~A:~D" sujet (vision:json-object-get p "confirmee_a"))))))
      ;; Archive préexistante synthétique : le chiffrement age n'est pas qualifié ici.
      (mrjam-courriel:ajouter file cle "operator@example.test" "Registre synthétique" "Intention synthétique")
      (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) (error "Relais arrêté")))
      (assert (= 202 (mrjam-metier::traiter-fermeture ctx secret "POST" "/fermer" headers body)))
      (assert (null (vision:json-object-get (vision-admission::sql admission :identifier mrjam-identite:issuer sujet) "erreur")))
      (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) t))
      (mrjam-courriel:traiter file smtp :cle cle :maintenant (+ (mrjam-courriel:maintenant) 3601))
      (assert (= 200 (mrjam-metier::traiter-fermeture ctx secret "POST" "/fermer" headers body)))
      (assert (vision:json-object-get (vision-admission::sql admission :identifier mrjam-identite:issuer sujet) "erreur"))
      (assert (null (vision-admission::ouvrir admission (lambda (db) (mrjam-native:sqlite-requete db "SELECT id FROM demandes WHERE sujet=?" (list sujet))))))
      (vision-fermeture::retirer-identite ctx sujet)
      (vision-fermeture::retirer-identite ctx sujet)
      (assert (= 404 (mrjam-identite:reponse-statut (mrjam-identite:requete client "GET" (concatenate 'string "/admin/realms/mrjam/users/" sujet) :token (mrjam-identite:autorisation client)))))
      (assert (null (vision:json-object-get (vision-admission::sql admission :identifier mrjam-identite:issuer "sujet-alice") "erreur")))))
  (format t "Fermeture : hook refusé sans secret, confirmation, registre préalable, effacement ciblé, admission purgée et retrait IdP idempotent qualifiés hors production.~%"))
