(defpackage #:gestion-differentiel (:use #:cl) (:export #:verifier))
(in-package #:gestion-differentiel)
(defun verifier (fichier)
  (let ((n 0))
    (dolist (c (vision:json-array-items (vision:parse-json (uiop:read-file-string fichier))))
      (let ((ok (handler-case (progn (vision-administration:verifier (vision:json-object-get c "op") (vision:json-object-get c "p")) t)
                  (vision-administration:parametres-invalides () nil))))
        (assert (eql ok (eq :true (vision:json-object-get c "ok"))) () "Cas administratif synthétique ~D divergent." n)) (incf n))
    (format t "~D validations administratives différentielles réussies.~%" n)))
