(defpackage #:matheval-composant (:use #:cl) (:export #:verifier))
(in-package #:matheval-composant)

(defun normaliser (v)
  (cond ((vision:json-array-p v) (vision::%make-json-array (mapcar #'normaliser (vision:json-array-items v))))
        ((vision:json-object-p v)
         (vision::%make-json-object (loop for (k . x) in (vision:json-object-entries v) collect
           (cons k (if (and (member k '("startedAt" "completedAt" "savedAt" "started_at" "updated_at" "completed_at" "imported_at") :test #'equal)
                            (not (eq x :null))) "<date>" (normaliser x))))))
        (t v)))

(defun verifier-concurrence (contexte banque)
  (let* ((id "24680abc-4321-4567-89ab-24680abc4321") (secret (make-string 64 :initial-element #\c))
         (create (vision:jobject "id" id "secret" secret "bankVersion" (matheval::champ banque "version")
                                 "levels" (vision:jarray (matheval::champ (first (vision:json-array-items (matheval::champ banque "questions"))) "level")) "seed" 17))
         (session (matheval:creer-session contexte create))
         (q (first (vision:json-array-items (matheval::champ session "questions"))))
         (p (first (vision:json-array-items (matheval::champ q "productions"))))
         (payload (lambda (note)
                    (vision:jobject "revision" 1 "final" :false "events" (vision:jarray)
                     "snapshot" (vision:jobject "answers" (vision:jobject (matheval::champ p "id")
                                  (vision:jobject "note" note "initialNote" note "coordinates" (vision:jobject "x" 0 "y" 0 "z" 0) "evaluatedAxes" (vision:jarray "x")))
                      "skippedQuestions" (vision:jarray) "progress" (vision:jobject "mode" "running" "index" 0 "selected" (matheval::champ p "id")
                        "exposed" (vision:jobject) "reader" :false "tour" -1)))))
         (depart (sb-thread:make-semaphore :count 0))
         (threads (loop for note in '(0 1) collect
                    (let ((data (funcall payload note)))
                      (sb-thread:make-thread (lambda ()
                        (sb-thread:wait-on-semaphore depart)
                        (handler-case (progn (matheval:sauvegarder-session contexte id secret data) 200)
                          (matheval:validation-error (e) (matheval:validation-status e)))))))))
    (sb-thread:signal-semaphore depart 2)
    (assert (equal '(200 409) (sort (mapcar #'sb-thread:join-thread threads) #'<)))
    (let* ((saved (matheval:lire-session contexte id secret))
           (note (matheval::champ (matheval::champ (matheval::champ (matheval::champ saved "snapshot") "answers") (matheval::champ p "id")) "note"))
           (same (funcall payload note))
           (dups (loop repeat 8 collect (sb-thread:make-thread (lambda () (matheval:sauvegarder-session contexte id secret same))))))
      (dolist (thread dups) (assert (= 1 (matheval::champ (sb-thread:join-thread thread) "revision")))))
    (assert (eq :null (matheval::champ (matheval:lire-session contexte id secret) "completedAt")))
    (assert (= 401 (handler-case (progn (matheval:lire-session contexte id (make-string 64 :initial-element #\a)) 200)
                    (matheval:validation-error (e) (matheval:validation-status e)))))
    (format t "Concurrence : un gagnant/un conflit, huit retransmissions identiques, secrets isolés.~%")))

(defun verifier (fichier)
  (let* ((fixture (vision:parse-json (uiop:read-file-string fichier)))
         (contexte (matheval:faire-contexte :connexion (vision:json-object-get fixture "connexion")
                    :version (vision:json-object-get fixture "version") :activation (vision:json-object-get fixture "activation")))
         (cookies (make-hash-table :test #'equal)) (n 0))
    (dolist (cas (vision:json-array-items (vision:json-object-get fixture "cases")))
      (let* ((path (vision:json-object-get cas "path")) (qmark (position #\? path))
             (url (concatenate 'string "http://127.0.0.1/" path))
             (query (vision::%make-json-object
                       (when qmark (loop for part in (uiop:split-string (subseq path (1+ qmark)) :separator "&")
                                         for eq = (position #\= part) collect (cons (subseq part 0 eq) (if eq (subseq part (1+ eq)) ""))))))
             (headers (copy-list (vision:json-object-entries (vision:json-object-get cas "headers"))))
             (cookie-ref (vision:json-object-get cas "cookieRef")))
        (declare (ignore url))
        (unless (eq cookie-ref :null) (push (cons "Cookie" (gethash cookie-ref cookies)) headers))
        (multiple-value-bind (status body retour)
            (mrjam-metier:traiter-matheval contexte (vision:json-object-get cas "method")
                                         (subseq path 0 qmark) headers query (vision:json-object-get cas "data")
                                         :origine "http://127.0.0.1:4173")
          (let ((expect (vision:json-object-get cas "expected")) (set (vision:json-object-get cas "setCookie")))
            (unless (and (= status (vision:json-object-get expect "status"))
                         (matheval::egal-json-p (normaliser body) (vision:json-object-get expect "body")))
              ;; Ne journaliser ni credentials ni contenus (même fixture).
              (error "Cas ~D route ~A : status ~D (attendu ~D), corps identique ~A"
                     n path status (vision:json-object-get expect "status")
                     (matheval::egal-json-p (normaliser body) (vision:json-object-get expect "body"))))
            (unless (eq set :null)
              (let ((c (cdr (assoc "Set-Cookie" retour :test #'string-equal))))
                (assert (and (search "HttpOnly" c) (search "SameSite=Strict" c) (search "Path=/matheval/api/admin" c)))
                (setf (gethash set cookies) (subseq c 0 (position #\; c)))))
            (incf n)))))
    (matheval::avec-base contexte
      (lambda (c)
        (let* ((ligne (matheval::un-json c "SELECT row_to_json(t)::text FROM (SELECT payload_hash,token_hash FROM participations WHERE id=$1::uuid) t"
                                        (list (vision:json-object-get fixture "id"))))
               (corpus (matheval::un-json c "SELECT row_to_json(t)::text FROM (SELECT digest,bank,codebook FROM corpus WHERE version=$1) t"
                                         (list (vision:json-object-get fixture "version")))))
          (assert (matheval::egal-json-p ligne (vision:json-object-get fixture "empreintes")))
          (assert (equal (matheval::champ corpus "digest") (vision:json-object-get fixture "corpusDigest")))
          (let ((banque (vision:parse-json (uiop:read-file-string (vision:json-object-get fixture "bankPath"))))
                (codes (vision:parse-json (uiop:read-file-string (vision:json-object-get fixture "codebookPath")))))
            (matheval:importer-corpus contexte banque codes)
            (verifier-concurrence contexte banque)))))
    (format t "~D parcours PostgreSQL/HTTP conformes à la référence, rôle non propriétaire.~%" n)))
