(defpackage #:native-differentiel (:use #:cl) (:export #:verifier))
(in-package #:native-differentiel)
(defun verifier (fichier)
  (let ((n 0))
    (dolist (c (vision:json-array-items (vision:parse-json (uiop:read-file-string fichier))))
      (let* ((op (vision:json-object-get c "op"))
             (actual (cond ((equal op "json") (mrjam-native:json-js (vision:parse-json (vision:json-object-get c "input"))))
                           ((equal op "sha256") (mrjam-native:sha256 (vision:json-object-get c "text")))
                           ((equal op "scrypt") (mrjam-native:scrypt (vision:json-object-get c "password") (vision:json-object-get c "salt"))))))
        (unless (equal actual (vision:json-object-get c "expected"))
          (error "Cas natif ~D (~A) divergent." n op)) (incf n)))
    (assert (mrjam-native:secret-egal-p "abc" "abc"))
    (assert (not (mrjam-native:secret-egal-p "abc" "abd")))
    (assert (not (mrjam-native:mot-de-passe-verifier "synthétique" "scrypt:malformé")))
    (assert (= 64 (length (mrjam-native:aleatoire-hex))))
    (let ((mrjam-native::*places-scrypt* (sb-thread:make-semaphore :count 0)))
      (assert (handler-case (progn (mrjam-native:scrypt "synthétique" "sel-synthétique") nil)
                (mrjam-native:native-error (e) (eq :capacite-scrypt (mrjam-native::native-operation e))))))
    (assert (= 2 (sb-thread:semaphore-count mrjam-native::*places-scrypt*)))
    (format t "~D cas différentiels OpenSSL/JSON binaire64 vérifiés.~%" n)))
