(load (merge-pathnames "../assemblage/charger.lisp" *load-truename*))
(asdf:load-system "mrjam-metier")
(dolist (adresse '(":::" "256.0.0.1" "127.1" "001.0.0.1" "2001:db8::x" "::1%lo"))
  (assert (null (mrjam-metier::quota-adresse adresse))))
(assert (equal "2001:db8:12::/56" (mrjam-metier::quota-adresse "2001:db8:12:ff::1")))
(assert (equal (mrjam-metier::quota-adresse "2001:DB8:12:ff::1")
               (mrjam-metier::quota-adresse "2001:db8:12::ffff")))
(assert (equal "192.0.2.2" (mrjam-metier::quota-adresse "::ffff:192.0.2.2")))
(assert (equal "192.0.2.2" (mrjam-metier::quota-adresse "::192.0.2.2")))
(let ((q (mrjam-metier::faire-quotas))
      (route (mrjam-metier::quota-route "POST" "/matheval/api/admin/login")))
  (assert (equal route (mrjam-metier::quota-route "POST" "/matheval/api/admin/setup")))
  (assert (null (mrjam-metier::quota-route "GET" "/matheval/api/health")))
  (dotimes (i 8) (assert (mrjam-metier::quota-prendre q route "127.0.0.1" 0)))
  (multiple-value-bind (ok reste compte raison) (mrjam-metier::quota-prendre q route "127.0.0.1" 0)
    (assert (not ok)) (assert (= reste 900)) (assert (zerop compte)) (assert (eq raison :limite)))
  (assert (mrjam-metier::quota-prendre q route "::1" 0))
  (assert (mrjam-metier::quota-prendre q route "127.0.0.1" (* 900 internal-time-units-per-second)))
  (assert (not (mrjam-metier::quota-prendre q route "adresse-forgee" 0)))
  (setf (mrjam-metier::quotas-maximum q) 2)
  (multiple-value-bind (ok attente n raison) (mrjam-metier::quota-prendre q route "192.0.2.2" 0)
    (declare (ignore attente n)) (assert (not ok)) (assert (eq raison :capacite)))
  (assert (mrjam-metier::quota-prendre q route "192.0.2.2" (* 1800 internal-time-units-per-second))))
;; Une course ne dépasse jamais le budget même avec des requêtes simultanées.
(let ((q (mrjam-metier::faire-quotas)) (garde (sb-thread:make-mutex)) (succes 0) threads)
  (dotimes (i 20)
    (push (sb-thread:make-thread (lambda ()
        (when (mrjam-metier::quota-prendre q '("connexion" 8 900) "198.51.100.2" 0)
          (sb-thread:with-mutex (garde) (incf succes))))) threads))
  (mapc #'sb-thread:join-thread threads) (assert (= 8 succes)))
(format t "Quotas HTTP : fenêtres historiques, budget partagé, isolation IP, capacité bornée et concurrence réussis.~%")
