(defpackage #:vision-cycle-test (:use #:cl) (:export #:verifier))
(in-package #:vision-cycle-test)
(defun verifier (dsn root)
  (flet ((role (r) (substitute #\Space #\Space (format nil "~A~A" (subseq dsn 0 (search "user=vision " dsn))
                                     (concatenate 'string "user=" r " dbname=vision_native_test")))))
    (let* ((admin (role "vision_administration")) (cycle-dsn (role "vision_cycle"))
           (headers '(("x-mrj-user" . "alice") ("x-vision-administration" . "1") ("content-type" . "application/json"))))
      (multiple-value-bind (status value) (mrjam-metier::traiter-gestion admin "POST" "/api/gestion/lister_comptes" headers "{}")
        (declare (ignore value)) (assert (= status 200)))
      (assert (= 401 (mrjam-metier::traiter-gestion admin "POST" "/api/gestion/lister_comptes" nil "{}")))
      (assert (= 403 (mrjam-metier::traiter-gestion admin "POST" "/api/gestion/lister_comptes"
                      (acons "x-mrj-user" "bob" (rest headers)) "{}")))
      (assert (= 400 (mrjam-metier::traiter-gestion admin "POST" "/api/gestion/modifier_compte" headers "{\"utilisateur\":\"bob\",\"version\":1,\"acteur\":\"alice\"}")))
      ;; Le rôle administratif n'a aucun accès aux contenus, même si Alice administre.
      (assert (handler-case (progn (mrjam-native:avec-connexion admin (lambda (c) (mrjam-native:requete c "SELECT contenu FROM public.vision_fiches"))) nil)
                (mrjam-native:database-error () t)))
      (vision-administration:administrer admin "alice" "demander_suppression" (vision:jobject "utilisateur" "bob" "version" 1))
      (let* ((smtp (vision:jobject "host" "smtp.protonmail.ch" "port" 587 "username" "sender@example.test" "password" "SyntheseSMTP2026Token"
                                   "from_address" "sender@example.test" "starttls_required" :true "certificate_verification" :true))
             (ctx (vision-cycle:faire-cycle cycle-dsn (merge-pathnames "cycle/" (uiop:ensure-directory-pathname root)) smtp
                     (vision:jobject "adresse_exploitant" "operator@example.test" "recipient_age" (concatenate 'string "age1" (make-string 58 :initial-element #\q)))
                     (lambda (d) (declare (ignore d)) "bob@example.test") "/usr/bin/false"))
             (file (vision-cycle::cycle-file ctx))
             (d (first (vision-cycle::preavis ctx))))
        (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) t))
        (assert (eq :false (vision-cycle::sql ctx :engager "bob" (vision:json-object-get d "id"))))
        (vision-cycle:traiter ctx)
        (assert (equal "accepte_relais" (vision:json-object-get (first (vision-cycle::preavis ctx)) "etat_courriel")))
        ;; Le préavis futur ne devient pas exigible pour simplifier une migration.
        (assert (eq :false (vision-cycle::sql ctx :engager "bob" (vision:json-object-get d "id"))))
        (let* ((date (vision-cycle::consigner ctx "bob"))
               (key (concatenate 'string "effacement:" (mrjam-native:sha256 (format nil "bob:~D" date)))))
          ;; Archive synthétique déjà préparée : ne pas prétendre qualifier age absent ici.
          (mrjam-courriel:ajouter file key "operator@example.test" "Registre synthétique" "Intention synthétique")
          (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) (error "Relais arrêté")))
          (assert (eq :true (vision:json-object-get (vision-cycle:effacer ctx "bob" "EFFACER VISION") "effacement_en_attente")))
          (assert (equal "Texte Bob" (vision:json-object-get (vision:parse-json
                            (cdar (first (mrjam-native:avec-connexion dsn (lambda (c)
                              (mrjam-native:transaction c (lambda (c)
                                (mrjam-native:requete c "SELECT set_config('vision.utilisateur','bob',true)")
                                (mrjam-native:requete c "SELECT jsonb_build_object('contenu',contenu) FROM vision_fiches")))))))) "contenu")))
          (setf (mrjam-courriel::file-transport file) (lambda (c m) (declare (ignore c m)) t))
          (mrjam-courriel:traiter file smtp :cle key :maintenant (+ (mrjam-courriel:maintenant) 3601))
          (assert (eq :true (vision:json-object-get (vision-cycle:effacer ctx "bob" "EFFACER VISION") "efface")))
          (assert (eq :true (vision:json-object-get (vision-cycle:effacer ctx "bob" "EFFACER VISION") "identite_commune_conservee")))
          (vision-cycle:traiter ctx)))))
  (format t "Administration et cycle : autorisations SQL, préavis futur et données conservés avant acceptation du registre ; reprise idempotente réussie.~%"))
