(in-package #:mrjam-metier)
(defun traiter-admission (ctx method path headers body)
  (labels ((reply (status code) (values status (vision:jobject "erreur" code))))
    (unless (equal (entete headers "origin") "https://vision.mrj.am") (return-from traiter-admission (reply 403 "origine_refusee")))
    (unless (equal method "POST") (return-from traiter-admission (reply 405 "operation_inconnue")))
    (unless (equal (first (uiop:split-string (or (entete headers "content-type") "") :separator ";")) "application/json")
      (return-from traiter-admission (reply 415 "json_requis")))
    (unless (<= 1 (length (sb-ext:string-to-octets body :external-format :utf-8)) 4096)
      (return-from traiter-admission (reply 400 "demande_invalide_ou_indisponible")))
    (unless ctx (return-from traiter-admission (reply 503 "admission_indisponible")))
    (handler-case
        (let ((p (vision:parse-json body)))
          (cond ((equal path "/auth/admission") (values 202 (vision-admission:demander ctx p)))
                ((and (equal path "/auth/admission/apercu") (mrjam-courriel::champs-p p '("token")))
                 (values 200 (vision-admission:apercu ctx (vision:json-object-get p "token"))))
                ((and (equal path "/auth/admission/confirmer") (mrjam-courriel::champs-p p '("token" "acceptation")))
                 (values 200 (vision-admission:confirmer ctx (vision:json-object-get p "token") (vision:json-object-get p "acceptation"))))
                (t (reply 400 "demande_invalide_ou_indisponible"))))
      (vision-admission:admission-error () (reply 400 "demande_invalide_ou_indisponible"))
      (mrjam-courriel:courriel-error () (reply 400 "demande_invalide_ou_indisponible"))
      (vision::json-error () (reply 400 "demande_invalide_ou_indisponible"))
      (error () (reply 503 "admission_indisponible")))))

(defun traiter-fermeture (ctx secret method path headers body)
  (labels ((reply (status) (values status (if (member status '(200 202)) (vision:jobject "demande_enregistree" :true) (vision:jobject "erreur" "fermeture_indisponible")))))
    (unless (and secret (equal path "/fermer") (equal method "POST")
                 (mrjam-native:secret-egal-p (or (entete headers "authorization") "") (concatenate 'string "Bearer " secret)))
      (return-from traiter-fermeture (reply 403)))
    (unless (and (equal (entete headers "content-type") "application/json")
                 (<= 1 (length (sb-ext:string-to-octets body :external-format :utf-8)) 1024))
      (return-from traiter-fermeture (reply 400)))
    (handler-case
        (let ((p (vision:parse-json body)))
          (unless (and (mrjam-courriel::champs-p p '("emetteur" "sujet" "confirmation"))
                       (equal (vision:json-object-get p "emetteur") mrjam-identite:issuer))
            (return-from traiter-fermeture (reply 400)))
          (unless ctx (return-from traiter-fermeture (reply 503)))
          (reply (if (vision-fermeture:preparer ctx (vision:json-object-get p "sujet") (vision:json-object-get p "confirmation")) 200 202)))
      (vision::json-error () (reply 400)) (vision-fermeture:fermeture-error () (reply 400)) (error () (reply 503)))))
