(in-package #:mrjam-metier)

(defun entete (headers nom) (cdr (assoc nom headers :test #'string-equal)))
(defun cookie-admin (headers)
  (loop for part in (uiop:split-string (or (entete headers "cookie") "") :separator ";")
        for p = (string-trim '(#\Space #\Tab) part)
        when (uiop:string-prefix-p "matheval_admin=" p) return (subseq p 15)))

(defun traiter-matheval (contexte methode chemin headers query corps &key origine)
  "Adaptateur sans listener : le serveur commun possède transport et cycle de vie.
Retour status, valeur JSON/CSV, en-têtes. Pas d'état utilisateur global."
  (let ((cookie (cookie-admin headers)) (result-headers (list (cons "Cache-Control" "no-store"))))
    (labels ((repondre (valeur &optional (status 200)) (values status valeur result-headers))
             (refuser (status message) (error 'matheval:validation-error :status status :message message))
             (signin (fonction)
               (multiple-value-bind (r secret) (funcall fonction contexte corps cookie)
                 (push (cons "Set-Cookie" (format nil "matheval_admin=~A; Path=/matheval/api/admin; HttpOnly; SameSite=Strict; Max-Age=28800~A"
                                                  secret (if (uiop:string-prefix-p "https:" origine) "; Secure" ""))) result-headers)
                 (repondre r))))
      (handler-case
          (progn
            (unless (member methode '("GET" "HEAD") :test #'equal)
              (unless (and origine (equal (entete headers "origin") origine)
                           (equal (entete headers "x-matheval-request") "1")
                           (equal (string-downcase (string-trim '(#\Space) (first (uiop:split-string (or (entete headers "content-type") "") :separator ";")))) "application/json"))
                (refuser 403 "Origine de la requête refusée.")))
            (when (stringp corps)
              (when (> (length (sb-ext:string-to-octets corps :external-format :utf-8)) (* 5 1024 1024))
                (refuser 413 "Requête trop volumineuse."))
              (setf corps (if (zerop (length corps)) (vision:jobject) (vision:parse-json corps))))
            (let ((parts (uiop:split-string (string-trim "/" chemin) :separator "/")))
              (cond
                ((and (member methode '("GET" "HEAD") :test #'equal) (equal parts '("health")))
                 (matheval::avec-base contexte (lambda (c) (mrjam-native:requete c "SELECT 1")))
                 (repondre (vision:jobject "status" "ok" "version" (matheval::contexte-version contexte))))
                ((and (equal methode "POST") (equal parts '("sessions")))
                 (repondre (matheval:creer-session contexte corps) 201))
                ((and (equal (first parts) "sessions") (second parts))
                 (let ((id (second parts)) (secret (or (entete headers "x-session-token") "")))
                   (cond ((and (= 2 (length parts)) (member methode '("GET" "HEAD") :test #'equal))
                          (repondre (matheval:lire-session contexte id secret)))
                         ((and (= 2 (length parts)) (equal methode "PUT"))
                          (repondre (matheval:sauvegarder-session contexte id secret corps)))
                         ((and (equal (cddr parts) '("events")) (member methode '("GET" "HEAD") :test #'equal))
                          (repondre (matheval:lire-evenements contexte id secret)))
                         (t (matheval:lire-session contexte id secret) (refuser 404 "Ressource inconnue.")))))
                ((and (equal methode "POST") (equal parts '("admin" "setup"))) (signin #'matheval:activer-administrateur))
                ((and (equal methode "POST") (equal parts '("admin" "login"))) (signin #'matheval:connecter-administrateur))
                ((equal (first parts) "admin")
                 (cond
                   ((and (member methode '("GET" "HEAD") :test #'equal) (equal (rest parts) '("me")))
                    (repondre (matheval:administrateur-courant contexte cookie)))
                   ((and (equal methode "POST") (equal (rest parts) '("logout")))
                    (let ((r (matheval:deconnecter-administrateur contexte cookie)))
                      (push (cons "Set-Cookie" (format nil "matheval_admin=; Path=/matheval/api/admin; HttpOnly; SameSite=Strict; Max-Age=0~A"
                                                      (if (uiop:string-prefix-p "https:" origine) "; Secure" ""))) result-headers)
                      (repondre r)))
                   ((member methode '("GET" "HEAD") :test #'equal)
                    (cond
                      ((equal (rest parts) '("corpora")) (repondre (matheval:corpus-scientifiques contexte cookie)))
                      ((and (= (length parts) 3) (equal (second parts) "corpus"))
                       (repondre (matheval:corpus-scientifique contexte cookie (third parts))))
                      ((equal (rest parts) '("statistics")) (repondre (matheval:statistiques-scientifiques contexte cookie query)))
                      ((equal (rest parts) '("participations")) (repondre (matheval:participations-scientifiques contexte cookie query)))
                      ((and (= (length parts) 3) (equal (second parts) "participations"))
                       (repondre (matheval:participation-scientifique contexte cookie (third parts))))
                      ((and (= (length parts) 4) (equal (second parts) "productions") (equal (fourth parts) "answers"))
                       (repondre (matheval:reponses-scientifiques contexte cookie query (third parts))))
                      ((equal (rest parts) '("exports" "responses.csv"))
                       (push (cons "Content-Type" "text/csv; charset=utf-8") result-headers)
                       (push (cons "Content-Disposition" "attachment; filename=\"matheval-reponses.csv\"") result-headers)
                       (repondre (matheval:export-scientifique contexte cookie query)))
                      (t (matheval:administrateur-courant contexte cookie) (refuser 404 "Ressource inconnue."))))
                   (t (matheval:administrateur-courant contexte cookie) (refuser 404 "Ressource inconnue."))))
                (t (refuser 404 "Ressource inconnue.")))))
        (matheval:validation-error (e)
          (repondre (vision:jobject "error" (if (= 400 (matheval:validation-status e))
                                               "Données invalides. Vérifiez les champs et réessayez."
                                               (matheval:validation-message e))) (matheval:validation-status e)))
        (vision::json-error ()
          (repondre (vision:jobject "error" "Données invalides. Vérifiez les champs et réessayez.") 400))
        (mrjam-native:native-error ()
          (repondre (vision:jobject "error" "Service temporairement occupé. Réessayez dans quelques instants.") 503))
        (mrjam-native:database-error ()
          (repondre (vision:jobject "error" "Enregistrement temporairement indisponible. Vos réponses sont conservées sur cet appareil.") 500))))))
