(in-package #:mrjam-metier)

(defun traiter-gestion (dsn methode chemin headers corps)
  (labels ((reply (status code) (values status (vision:jobject "erreur" code))))
    (handler-case
        (progn
          (unless (and (equal (entete headers "x-vision-administration") "1")
                       (vision-administration:identifiant-p (entete headers "x-mrj-user")))
            (return-from traiter-gestion (reply 401 "identite_requise")))
          (unless (equal methode "POST") (return-from traiter-gestion (reply 405 "operation_inconnue")))
          (unless (equal (first (uiop:split-string (or (entete headers "content-type") "") :separator ";")) "application/json")
            (return-from traiter-gestion (reply 415 "json_requis")))
          (unless (and (uiop:string-prefix-p "/api/gestion/" chemin) (<= 1 (length (sb-ext:string-to-octets corps :external-format :utf-8)) 8192))
            (return-from traiter-gestion (reply 400 "parametres_invalides")))
          (unless dsn (return-from traiter-gestion (reply 503 "base_indisponible")))
          (values 200 (vision-administration:administrer dsn (entete headers "x-mrj-user") (subseq chemin 13) (vision:parse-json corps))))
      (vision-administration:parametres-invalides () (reply 400 "parametres_invalides"))
      (vision::json-error () (reply 400 "parametres_invalides"))
      (mrjam-native:database-error (e)
        (let ((code (mrjam-native:database-code e)))
          (cond (code (reply (cond ((equal code "administration_interdite") 403) ((equal code "conflit") 409) (t 400)) code))
                ((or (equal (mrjam-native:sqlstate e) "P0001") (uiop:string-prefix-p "23" (mrjam-native:sqlstate e)))
                 (reply 400 "parametres_invalides"))
                (t (reply 503 "base_indisponible"))))))))
