(in-package #:mrjam-metier)
(defun traiter-effacement (ctx methode headers corps)
  (labels ((reply (code erreur) (values code (vision:jobject "erreur" erreur))))
    (unless (and (equal (entete headers "x-vision-browser") "1") (equal (entete headers "x-vision-authenticated") "1")
                 (vision-administration:identifiant-p (entete headers "x-mrj-user")))
      (return-from traiter-effacement (reply 401 "identite_requise")))
    (unless (equal methode "POST") (return-from traiter-effacement (reply 405 "operation_inconnue")))
    (handler-case
        (progn
          (unless (and (equal (first (uiop:split-string (or (entete headers "content-type") "") :separator ";")) "application/json")
                       (<= 1 (length (sb-ext:string-to-octets corps :external-format :utf-8)) 1024))
            (return-from traiter-effacement (reply 400 "confirmation_requise")))
          (let ((p (vision:parse-json corps)))
            (unless (and (vision:json-object-p p) (= 1 (length (vision:json-object-entries p)))
                         (equal (vision:json-object-get p "confirmation") "EFFACER VISION"))
              (return-from traiter-effacement (reply 400 "confirmation_requise"))))
          (unless ctx (return-from traiter-effacement (reply 503 "effacement_indisponible")))
          (let ((result (vision-cycle:effacer ctx (entete headers "x-mrj-user") "EFFACER VISION")))
            (values (if (eq :true (vision:json-object-get result "effacement_en_attente")) 202 200) result)))
      (vision::json-error () (reply 400 "confirmation_requise"))
      (vision-cycle:cycle-error () (reply 400 "confirmation_requise"))
      (error () (reply 503 "effacement_indisponible")))))
