(in-package #:mrjam-courriel)

(defun adresse (s)
  (unless (and (stringp s) (<= 3 (length s) 254)) (refuse :adresse))
  (let* ((at (position #\@ s)) (dot (position #\. s :from-end t)) (domain (and at (subseq s (1+ at)))))
    (unless (and at (> at 0) (not (position #\@ s :start (1+ at))) dot (> dot (1+ at))
                 (ascii-p (subseq s 0 at) ".!#$%&'*+/=?^_`{|}~-" 1 254)
                 (ascii-p domain ".-" 1 254) (<= 2 (- (length s) dot 1) 63)
                 (every (lambda (c) (or (char<= #\a c #\z) (char<= #\A c #\Z))) (subseq s (1+ dot)))) (refuse :adresse)))
  s)

(defun normaliser-lignes (s)
  (with-output-to-string (o)
    (loop for i from 0 below (length s) for c = (char s i) do
      (if (char= c #\Return)
          (progn (write-char #\Newline o) (when (and (< (1+ i) (length s)) (char= (char s (1+ i)) #\Newline)) (incf i)))
          (write-char c o)))))
(defun texte-normalise (s)
  (let ((s (normaliser-lignes s)))
    (if (and (> (length s) 0) (char= (char s (1- (length s))) #\Newline)) s (concatenate 'string s (string #\Newline)))))
(defun crlf (s)
  (with-output-to-string (o) (loop for c across s do (when (char= c #\Newline) (write-char #\Return o)) (write-char c o))))

(defun de-base64 (text)
  (let ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)) (bits 0) (n 0) (fin nil))
    (loop for c across text unless (find c '(#\Space #\Tab #\Newline #\Return)) do
      (cond ((char= c #\=) (setf fin t))
            (fin (refuse :base64))
            (t (let ((v (position c "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")))
                 (unless v (refuse :base64)) (setf bits (logior (ash bits 6) v)) (incf n 6)
                 (when (>= n 8) (decf n 8) (vector-push-extend (ldb (byte 8 n) bits) out)
                   (setf bits (ldb (byte n 0) bits)))))))
    (unless (and (< n 6) (zerop bits)) (refuse :base64)) (coerce out '(simple-array (unsigned-byte 8) (*)))))
(defun de-qp (text &key entete)
  (let ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (loop for i from 0 below (length text) for c = (char text i) do
      (cond ((and entete (char= c #\_)) (vector-push-extend 32 out))
            ((char= c #\=)
             (cond ((and (not entete) (< (1+ i) (length text)) (char= (char text (1+ i)) #\Newline)) (incf i))
                   ((and (< (+ i 2) (length text)) (digit-char-p (char text (1+ i)) 16) (digit-char-p (char text (+ i 2)) 16))
                    (vector-push-extend (+ (* 16 (digit-char-p (char text (1+ i)) 16)) (digit-char-p (char text (+ i 2)) 16)) out) (incf i 2))
                   (t (refuse :quoted-printable))))
            ((<= (char-code c) 255) (vector-push-extend (char-code c) out)) (t (refuse :quoted-printable))))
    (coerce out '(simple-array (unsigned-byte 8) (*)))))

(defun sujet-decode (s)
  (with-output-to-string (o)
    (loop with i = 0 while (< i (length s)) for debut = (search "=?" s :start2 i) do
      (unless debut (write-string s o :start i) (return))
      (write-string s o :start i :end debut)
      (let* ((a (position #\? s :start (+ debut 2))) (b (and a (position #\? s :start (1+ a))))
             (fin (and b (search "?=" s :start2 (1+ b)))))
        (unless (and a b fin (member (string-downcase (subseq s (+ debut 2) a)) '("utf-8" "us-ascii") :test #'equal)) (refuse :entete-mime))
        (let* ((coding (string-upcase (subseq s (1+ a) b))) (text (subseq s (1+ b) fin))
               (bytes (cond ((equal coding "B") (de-base64 text)) ((equal coding "Q") (de-qp text :entete t)) (t (refuse :entete-mime)))))
          (write-string (sb-ext:octets-to-string bytes :external-format :utf-8) o))
        (setf i (+ fin 2))
        (let ((next (position-if-not (lambda (c) (find c '(#\Space #\Tab))) s :start i)))
          (when (and next (<= (+ next 2) (length s)) (string= "=?" s :start2 next :end2 (+ next 2))) (setf i next)))))))

(defun separer-mime (text)
  (let* ((fin (search (format nil "~%~%") text)) (headers nil))
    (unless fin (refuse :mime))
    (dolist (line (uiop:split-string (subseq text 0 fin) :separator (string #\Newline)))
      (if (and (> (length line) 0) (find (char line 0) '(#\Space #\Tab)))
          (progn (unless headers (refuse :mime)) (setf (cdar headers) (concatenate 'string (cdar headers) " " (string-left-trim '(#\Space #\Tab) line))))
          (let ((colon (position #\: line)))
            (unless colon (refuse :mime))
            (push (cons (string-downcase (subseq line 0 colon)) (string-left-trim '(#\Space) (subseq line (1+ colon)))) headers))))
    (values headers (subseq text (+ fin 2)))))
(defun parametre-mime (s nom)
  (let ((pairs (loop for p in (rest (uiop:split-string s :separator ";")) for v = (string-trim '(#\Space) p)
                    for eq = (position #\= v) when eq collect (cons (string-downcase (subseq v 0 eq)) (string-trim '(#\") (subseq v (1+ eq)))))))
    (or (cdr (assoc nom pairs :test #'equal))
        ;; Python replie la frontière déterministe de 70 caractères en RFC2231.
        (when (assoc (concatenate 'string nom "*0*") pairs :test #'equal)
          (with-output-to-string (o)
            (loop for n from 0 below 10 for key = (format nil "~A*~D*" nom n)
                  for part = (cdr (assoc key pairs :test #'equal)) while part do
              (when (zerop n)
                (unless (uiop:string-prefix-p "us-ascii''" part) (refuse :parametre-mime))
                (setf part (subseq part 10)))
              (loop for i from 0 below (length part) for c = (char part i) do
                (if (char= c #\%)
                    (progn (unless (and (< (+ i 2) (length part)) (digit-char-p (char part (1+ i)) 16) (digit-char-p (char part (+ i 2)) 16)) (refuse :parametre-mime))
                           (write-char (code-char (+ (* 16 (digit-char-p (char part (1+ i)) 16)) (digit-char-p (char part (+ i 2)) 16))) o) (incf i 2))
                    (write-char c o)))))))))
(defun partie-octets (headers body)
  (let ((coding (string-downcase (or (cdr (assoc "content-transfer-encoding" headers :test #'equal)) "7bit"))))
    (cond ((equal coding "base64") (de-base64 body)) ((equal coding "quoted-printable") (de-qp body))
          ((member coding '("7bit" "8bit") :test #'equal) (sb-ext:string-to-octets body :external-format :utf-8))
          (t (refuse :mime)))))

(defun ancien-contenu (bytes)
  "Lecteur borné des seuls messages text/plain/multipart générés par l'ancien auxiliaire.
Un MIME inconnu est refusé, jamais écrasé avec le même identifiant."
  (multiple-value-bind (h body) (separer-mime (normaliser-lignes (sb-ext:octets-to-string bytes :external-format :utf-8)))
    (let* ((ctype (or (cdr (assoc "content-type" h :test #'equal)) "text/plain")) (texte nil) (piece nil))
      (if (uiop:string-prefix-p "multipart/mixed" ctype)
          (let* ((b (parametre-mime ctype "boundary")) (delim (and b (concatenate 'string "--" b))))
            (unless (and b (<= 1 (length b) 120)) (refuse :mime))
            (loop with start = 0 for debut = (search delim body :start2 start) while debut do
              (let ((a (+ debut (length delim))))
                (when (and (<= (+ a 2) (length body)) (string= "--" body :start2 a :end2 (+ a 2))) (return))
                (unless (and (< a (length body)) (char= (char body a) #\Newline)) (refuse :mime))
                (let* ((fin (search (concatenate 'string (string #\Newline) delim) body :start2 (1+ a))))
                  (unless fin (refuse :mime))
                  (multiple-value-bind (ph pb) (separer-mime (subseq body (1+ a) fin))
                    (let ((ct (cdr (assoc "content-type" ph :test #'equal))))
                      (cond ((and ct (uiop:string-prefix-p "text/plain" ct) (null texte))
                             (setf texte (sb-ext:octets-to-string (partie-octets ph pb) :external-format :utf-8)))
                            ((and ct (equal ct "application/octet-stream") (null piece)) (setf piece (partie-octets ph pb)))
                            (t (refuse :mime)))))
                  (setf start (1+ fin))))))
          (progn (unless (uiop:string-prefix-p "text/plain" ctype) (refuse :mime))
                 (setf texte (sb-ext:octets-to-string (partie-octets h body) :external-format :utf-8))))
      (unless texte (refuse :mime))
      (list (cdr (assoc "from" h :test #'equal)) (cdr (assoc "to" h :test #'equal))
            (sujet-decode (or (cdr (assoc "subject" h :test #'equal)) "")) (texte-normalise texte) piece))))

(defun empreinte-contenu (de a sujet texte piece)
  (mrjam-native:sha256 (mrjam-native:json-js (vision:jarray de a sujet (texte-normalise texte)
                                (if piece (mrjam-native:base64 piece) :null)))))
(defun base64-lignes (bytes)
  (let ((s (mrjam-native:base64 bytes)))
    (with-output-to-string (o) (loop for i from 0 below (length s) by 76 do
      (write-line (subseq s i (min (+ i 76) (length s))) o)))))
(defun sujet-encode (s)
  (if (and (< (length s) 65) (every (lambda (c) (<= 32 (char-code c) 126)) s)) s
      (let ((words nil) (current ""))
        (flet ((emit () (push (format nil "=?utf-8?B?~A?=" (mrjam-native:base64 (sb-ext:string-to-octets current :external-format :utf-8))) words) (setf current "")))
          (loop for c across s do
            (when (> (length (sb-ext:string-to-octets (concatenate 'string current (string c)) :external-format :utf-8)) 42) (emit))
            (setf current (concatenate 'string current (string c))))
          (when (> (length current) 0) (emit)))
        (format nil "~{~A~^~% ~}" (nreverse words)))))
(defun date-rfc (cree)
  (multiple-value-bind (ss mm hh d m y wd) (decode-universal-time (+ cree 2208988800) 0)
    (format nil "~A, ~2,'0D ~A ~4,'0D ~2,'0D:~2,'0D:~2,'0D +0000"
            (aref #("Mon" "Tue" "Wed" "Thu" "Fri" "Sat" "Sun") wd) d
            (aref #("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec") (1- m)) y hh mm ss)))
(defun message-mime (cle de a sujet texte piece cree)
  (let* ((hash (mrjam-native:sha256 cle)) (boundary (concatenate 'string "mrjam-" hash)))
    (sb-ext:string-to-octets
      (crlf (with-output-to-string (o)
        (format o "From: ~A~%To: ~A~%Subject: ~A~%Message-ID: <~A@mrj.am>~%Date: ~A~%MIME-Version: 1.0~%"
                de a (sujet-encode sujet) hash (date-rfc cree))
        (when piece (format o "Content-Type: multipart/mixed; boundary=~S~%~%--~A~%" boundary boundary))
        (format o "Content-Type: text/plain; charset=\"utf-8\"~%Content-Transfer-Encoding: base64~%~%~A"
                (base64-lignes (sb-ext:string-to-octets (texte-normalise texte) :external-format :utf-8)))
        (when piece
          (format o "~%--~A~%Content-Type: application/octet-stream~%Content-Transfer-Encoding: base64~%Content-Disposition: attachment; filename=\"effacement.json.age\"~%~%~A~%--~A--~%"
                  boundary (base64-lignes piece) boundary)))) :external-format :utf-8)))
